### ISSUE TITLE
Unable to use ClientAuthCode with string

### ISSUE THREAD

**Issue by cyupa** [sourcefuse/loopback4-authentication#10]
Shouldn't the ClientAuthCode be a number or a string? 
How can I use it with a use that has a UUID as a primary key?

https://github.com/sourcefuse/loopback4-authentication/blob/765e8123e7580170e2caabde0e9f7d2eda9e4f90/src/types.ts#L37

Thanks!

**Comment by samarpan-b** [comment]
Right now we are not supporting non integer primary keys. You can raise a feature request for the same. Or, if you like, you can raise a PR too.
