### ISSUE TITLE
Replace passport-apple with the official apple oauth strategy

### ISSUE THREAD

**Issue by akshatdubeysf** [sourcefuse/loopback4-authentication#126]
**Describe the bug**
The library currently uses the [passport-apple](https://www.npmjs.com/package/passport-apple) which is not maintained anymore. It's better to move to some better maintained library like https://www.npmjs.com/package/apple-signin-auth.

**Comment by yeshamavani** [comment]
Needs discussion

**Comment by yeshamavani** [comment]
@Surbhi-sharma1  please comment the issue we faced
