### ISSUE TITLE
Replace passport-keycloak with the keycloak-nodejs-connect.

### ISSUE THREAD

**Issue by Surbhi-sharma1** [sourcefuse/loopback4-authentication#155]
**Describe the bug**
The library currently uses the passport-keycloak which is not maintained anymore. It's better to move to some better maintained library like https://github.com/keycloak/keycloak-nodejs-connect.

**Comment by miguelcorreia19** [comment]
It's probably better to have a look at this [thread](https://github.com/keycloak/keycloak-nodejs-connect/issues/492), once keycloak-nodejs-connect is deprecated.
