### ISSUE TITLE
README clarity

### ISSUE THREAD

**Issue by yapalexei** [sourcefuse/loopback4-authentication#19]
**Description**
The README talks about implementing [Http-bearer](https://github.com/sourcefuse/loopback4-authentication#http-bearer) strategy that seems to have some missing imports ([RevokedTokenRepository](https://github.com/sourcefuse/loopback4-starter/blob/master/src/repositories/revoked-token.repository.ts)) for the `BearerTokenVerifyProvider` example. I eventually found them in the [starter project repo](https://github.com/sourcefuse/loopback4-starter) but thought, for posterity, it would be nice to have those imports mentioned and linked to either examples or illustrated before they are used. I, so far, was able to follow along and get things to work but got stuck here for a bit. Other wise this is a great tutorial, I love it! :)

**Comment by samarpanB** [comment]
That’s a good suggestion. I’ll try to get it fixed soon.
