### ISSUE TITLE
Allow use of email in place of username with passport local.

### ISSUE THREAD

**Issue by sidshrivastav** [sourcefuse/loopback4-authentication#22]
**Is your feature request related to a problem? Please describe.**
I want to use email instead of a username with a password.

**Describe the solution you'd like**
Something like this `https://github.com/jaredhanson/passport-local#parameters`

**Comment by samarpan-b** [comment]
You can easily use username to field to pass on email. Are you facing issues with that ?

**Comment by sidshrivastav** [comment]
Yes, can you provide any example for this?

**Comment by akshatdubeysf** [comment]
@sidshrivastav you can change the username/password field by passing options to the [Passport Strategy](http://www.passportjs.org/docs/username-password/) (see the parameters sections) - 

`
@authenticate(STRATEGY.LOCAL, {
    usernameField: 'email'
  })
`

Then you will get the email field value in the verifier binding and you can use that to authenticate the user.
