### ISSUE TITLE
Can we use MongoDB instead of Redis?

### ISSUE THREAD

**Issue by siva-nadella-lab** [sourcefuse/loopback4-authentication#220]
**Describe the bug**
According to the documentation and code, we see that Redis is used for RevokedTokenRepository and RefreshTokenRepository. Is this mandatory?

Can I use MongoDB instead?

**Comment by yeshamavani** [comment]
we are using keyvalue repository hence used redis

**Comment by siva-nadella-lab** [comment]
Understood... Thank you for your response. We are currently not seeing the need to use Redis for this purpose. Apart from it being a KeyValue pair, is there any other reason you have on why Redis or any other such caching utility is needed?

**Comment by yeshamavani** [comment]
Caching is the only reason we have used Redis
