### ISSUE TITLE
Loopback4 Bearer_Token authentication

### ISSUE THREAD

**Issue by sherif2011** [sourcefuse/loopback4-authentication#4]
Description / Steps to reproduce / Feature proposal

I tried following the example mentioned in https://www.npmjs.com/package/loopback4-authentication to get http-bearer configured.

Here is my simple project on Github: https://github.com/sherif2011/lb4_token

Current Behavior
When I run and try accessing localhost:3000, I get "500 JsonWebTokenError: jwt must be a string"

Expected Behavior
Expected to be able to access explorer and when I try to ping, would get an error: Unauthorized

Thank you!
Sherif

**Comment by samarpan-b** [comment]
Hello @sherif2011 ,

It seems that you have not followed through the usage documentation well. In you sequence.ts, I see this
```
    @inject(AuthenticationBindings.Passport.BEARER_TOKEN_VERIFIER)
    protected authenticateRequest: AuthenticateFn<User>,
```
This is wrong. Please have a look at the documentation for bearer strategy here - https://github.com/sourcefuse/loopback4-authentication#http-bearer

Hope this helps.

**Comment by samarpan-b** [comment]
Also, please do take latest version of the package. There has been some changes which you will need.

**Comment by samarpan-b** [comment]
@sherif2011 did it work ? Can I close this issue now ?

**Comment by sherif2011** [comment]
@samarpan-b can you please leave it open through this weekend? I will check and get back to you.

Thank you so much!!

**Comment by samarpan-b** [comment]
ok. no worries

**Comment by sherif2011** [comment]
So, I am running into several issues. 
1. RevokedTokenRepository: Do I need to create that model/repository? Does it matter what should it contain? I only included a jwt string field as id required, would that work?
2. In application.ts, 
this.bind(AuthenticationBindings.Passport.BEARER_TOKEN_VERIFIER).toProvider(
  BearerTokenVerifyProvider,
);

password isn't a property of AuthenticationBindings? It used to be, but maybe under a previous version?

**Comment by samarpanB** [comment]
1. This is a model which is saved in redis and is used to handle logout. Revoked tokens. If you don’t wanna go this approach, you can remove this altogether, remove all its references and checks and remove logout API.
2. Please use version 1.x.x for this to work. There has been a breaking change in 2.x.x which I still need to document.

**Comment by samarpan-b** [comment]
@sherif2011 you can refer to the updated documentation now.

**Comment by sherif2011** [comment]
Hello Samarpan-b,
I was able to setup and run this example: https://github.com/sourcefuse/loopback4-starter
It's working fine, and I was able to login using super_admin and retrieve access token (code). Now If I try passing Authorization: Bearer {Code} in header of get request of http://localhost:3000/users/count, I get 401 unauthorized. Not sure why, I even added (ViewAnyUser, ViewOwnUser, ViewTenantUser) in user_tenant_permissions table to make sure that super_admin has permission. Can you please advise?

**Comment by sherif2011** [comment]
btw, forgot to mention that I am calling the secured APIs using fiddler (alternative to postman)
Here is Get URL: http://localhost:3000/users/count
and this is the header: 
Content-Type: application/json;charset=UTF-8 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6IndlYmFwcCIsInVzZXJJZCI6MSwiaWF0IjoxNTYyNzgwNjcwLCJleHAiOjE1NjI3ODA4NTAsImF1ZCI6IndlYmFwcCIsImlzcyI6ImxiX2FwaSIsInN1YiI6InN1cGVyX2FkbWluIn0.7tmlpystOPjYUydvSLHDA2AO9pq4GhtYeqE7CWeWS90
Host: localhost:3000

And this is the response I am getting:
{"error":{"statusCode":401,"name":"UnauthorizedError","message":{"name":"JsonWebTokenError","message":"invalid signature"}}}

**Comment by sherif2011** [comment]
I guess the token is valid, but I can't figure out how to solve this 'invalid signature' issue. Thanks!

**Comment by samarpanB** [comment]
Let me check it tomorrow and get back to you.

**Comment by sherif2011** [comment]
Great, thank you!

**Comment by sherif2011** [comment]
Never mind, I was able to figure out the issue. I was trying to use the code returned from login api as access token. My bad!

Thank you!

**Comment by samarpan-b** [comment]
Cool. That's great. Let me know if you face any further issues.

**Comment by sherif2011** [comment]
Quick question, after logging in and getting access token, does the token include authorization info (role, permissions...etc)? What's the best way to read that?

**Comment by sherif2011** [comment]
Never mind, I see all permissions there after I decoded the token... I will search online to see what's a good node package to use for decoding. Thanks a bunch!

**Comment by samarpan-b** [comment]
@sherif2011 can we close this issue now, since you have been able to use it successfully ?

**Comment by samarpan-b** [comment]
Closing this due to non activity.

**Comment by mohammadfaisal1** [comment]
> Never mind, I was able to figure out the issue. I was trying to use the code returned from login api as access token. My bad!
> 
> Thank you!
so, what did you use for access token
