### ISSUE TITLE
Support lastest version of Loopback (mostly @loopback/rest@10.0.0)

### ISSUE THREAD

**Issue by arnaud16571542** [sourcefuse/loopback4-authentication#52]
**Is your feature request related to a problem? Please describe.**
Using last dependency version of loopback, with @loopback/rest@10.0.0, we can't do "npm install loopback4-authentication" because of an error : "unable to resolve dependency tree". Authentication's request loopback/rest@^9.3.0.

**Describe the solution you'd like**
Loopback4-authentication should be updated to use the lastest version of @loopback/rest@10.0.0,

**Describe alternatives you've considered**
Not using the lastes version of loopback4

**Additional context**
n/a

**Comment by akshatdubeysf** [comment]
Hi @arnaud16571542 ,

The "unable to resolve dependency tree" error is because of the updated way of resolving dependencies in npm v7, you can try to use the `--legacy-peer-deps` option to use the legacy method, or use the v6.

**Comment by akshatdubeysf** [comment]
The project has been updated hence closing this issue
